#!/usr/bin/env python3
"""Fetch V8 12.4.254.21 source and third-party dependencies.

Auto-generated by scripts/generate_fetch_deps.py
"""

import os
import subprocess
import sys

V8_VERSION = "12.4.254.21"
V8_REPO = "https://chromium.googlesource.com/v8/v8.git"
V8_TAG = "12.4.254.21"

DEPS = {
    "abseil-cpp": {
        "url": "https://chromium.googlesource.com/chromium/src/third_party/abseil-cpp.git",
        "commit": "b3ae305fd5dbc6ad41eed9add26768c29181219f",
        "path": "v8-src/third_party/abseil-cpp",
    },
    "fp16": {
        "url": "https://chromium.googlesource.com/external/github.com/Maratyszcza/FP16.git",
        "commit": "0a92994d729ff76a58f692d3028ca1b64b145d91",
        "path": "v8-src/third_party/fp16/src",
    },
    "googletest": {
        "url": "https://chromium.googlesource.com/external/github.com/google/googletest.git",
        "commit": "b479e7a3c161d7087113a05f8cb034b870313a55",
        "path": "v8-src/third_party/googletest/src",
    },
    "icu": {
        "url": "https://chromium.googlesource.com/chromium/deps/icu.git",
        "commit": "a622de35ac311c5ad390a7af80724634e5dc61ed",
        "path": "v8-src/third_party/icu",
    },
    "zlib": {
        "url": "https://chromium.googlesource.com/chromium/src/third_party/zlib.git",
        "commit": "c5bf1b566e5df14e763507e2ce30cbfebefeeccf",
        "path": "v8-src/third_party/zlib",
    },
}


def run(cmd, **kwargs):
    print(f"  $ {' '.join(cmd)}")
    subprocess.check_call(cmd, **kwargs)


def fetch_v8():
    if os.path.isdir("v8-src"):
        print("v8-src/ already exists, checking version...")
        # Could verify version here
        return
    print(f"Cloning V8 {V8_VERSION}...")
    run(["git", "clone", "--depth=1", "--branch", V8_TAG, V8_REPO, "v8-src"])


def fetch_deps():
    for name, info in DEPS.items():
        path = info["path"]
        if os.path.isdir(path):
            print(f"  {name}: already exists at {path}")
            continue
        print(f"  {name}: cloning...")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        run(["git", "clone", info["url"], path])
        run(["git", "checkout", info["commit"]], cwd=path)


def main():
    print(f"Fetching V8 {V8_VERSION} and dependencies...")
    fetch_v8()
    print("\nFetching third-party dependencies...")
    fetch_deps()
    print("\nDone!")


if __name__ == "__main__":
    main()
