#!/usr/bin/env python3
"""Fetch V8 9.4.146.26 source and third-party dependencies.

Auto-generated by scripts/generate_fetch_deps.py
"""

import os
import subprocess
import sys

V8_VERSION = "9.4.146.26"
V8_REPO = "https://chromium.googlesource.com/v8/v8.git"
V8_TAG = "9.4.146.26"

DEPS = {
    "googletest": {
        "url": "https://chromium.googlesource.com/external/github.com/google/googletest.git",
        "commit": "47f819c3ca54fb602f432904443e00a0a1fe2f42",
        "path": "v8-src/third_party/googletest/src",
    },
    "icu": {
        "url": "https://chromium.googlesource.com/chromium/deps/icu.git",
        "commit": "75e34bcccea0be165c31fdb278b3712c516c5876",
        "path": "v8-src/third_party/icu",
    },
    "zlib": {
        "url": "https://chromium.googlesource.com/chromium/src/third_party/zlib.git",
        "commit": "563140dd9c24f84bf40919196e9e7666d351cc0d",
        "path": "v8-src/third_party/zlib",
    },
}


def run(cmd, **kwargs):
    print(f"  $ {' '.join(cmd)}")
    subprocess.check_call(cmd, **kwargs)


def fetch_v8():
    if os.path.isdir("v8-src"):
        print("v8-src/ already exists, checking version...")
        # Could verify version here
        return
    print(f"Cloning V8 {V8_VERSION}...")
    run(["git", "clone", "--depth=1", "--branch", V8_TAG, V8_REPO, "v8-src"])


def fetch_deps():
    for name, info in DEPS.items():
        path = info["path"]
        if os.path.isdir(path):
            print(f"  {name}: already exists at {path}")
            continue
        print(f"  {name}: cloning...")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        run(["git", "clone", info["url"], path])
        run(["git", "checkout", info["commit"]], cwd=path)


def main():
    print(f"Fetching V8 {V8_VERSION} and dependencies...")
    fetch_v8()
    print("\nFetching third-party dependencies...")
    fetch_deps()
    print("\nDone!")


if __name__ == "__main__":
    main()
