#!/usr/bin/env python3
"""Fetch V8 11.3.244.8 source and third-party dependencies.

Auto-generated by scripts/generate_fetch_deps.py
"""

import os
import subprocess
import sys

V8_VERSION = "11.3.244.8"
V8_REPO = "https://chromium.googlesource.com/v8/v8.git"
V8_TAG = "11.3.244.8"

DEPS = {
    "googletest": {
        "url": "https://chromium.googlesource.com/external/github.com/google/googletest.git",
        "commit": "af29db7ec28d6df1c7f0f745186884091e602e07",
        "path": "v8-src/third_party/googletest/src",
    },
    "icu": {
        "url": "https://chromium.googlesource.com/chromium/deps/icu.git",
        "commit": "1e49ac26ddc712b1ab702f69023cbc57e9ae6628",
        "path": "v8-src/third_party/icu",
    },
    "zlib": {
        "url": "https://chromium.googlesource.com/chromium/src/third_party/zlib.git",
        "commit": "5edb52d4302d7aef232d585ec9ae27ef5c3c5438",
        "path": "v8-src/third_party/zlib",
    },
}


def run(cmd, **kwargs):
    print(f"  $ {' '.join(cmd)}")
    subprocess.check_call(cmd, **kwargs)


def fetch_v8():
    if os.path.isdir("v8-src"):
        print("v8-src/ already exists, checking version...")
        # Could verify version here
        return
    print(f"Cloning V8 {V8_VERSION}...")
    run(["git", "clone", "--depth=1", "--branch", V8_TAG, V8_REPO, "v8-src"])


def fetch_deps():
    for name, info in DEPS.items():
        path = info["path"]
        if os.path.isdir(path):
            print(f"  {name}: already exists at {path}")
            continue
        print(f"  {name}: cloning...")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        run(["git", "clone", info["url"], path])
        run(["git", "checkout", info["commit"]], cwd=path)


def main():
    print(f"Fetching V8 {V8_VERSION} and dependencies...")
    fetch_v8()
    print("\nFetching third-party dependencies...")
    fetch_deps()
    print("\nDone!")


if __name__ == "__main__":
    main()
