#!/usr/bin/env python3
"""Generate cmake/sources.cmake by parsing V8 BUILD.gn files.

Uses parse_gn.py to extract source file lists for each V8 library target,
filtered for Windows x64 platform.
"""

import argparse
import json
import os
import sys
from datetime import datetime

# Add scripts dir to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from parse_gn import GnParser, GnCondition


# Map GN target names to CMake variable names
TARGET_MAP = {
    # GN target name -> (cmake_var, cmake_target)
    "v8_libbase": ("V8_LIBBASE_SOURCES", "v8_libbase"),
    "v8_libplatform": ("V8_LIBPLATFORM_SOURCES", "v8_libplatform"),
    "v8_libsampler": ("V8_LIBSAMPLER_SOURCES", "v8_libsampler"),
    "v8_bigint": ("V8_BIGINT_SOURCES", "v8_bigint"),
    "v8_heap_base": ("V8_HEAP_BASE_SOURCES", "v8_heap_base"),
    "cppgc_base": ("V8_HEAP_BASE_SOURCES", "v8_heap_base"),  # older name
    "v8_cppgc_shared": ("V8_CPPGC_SOURCES", "v8_cppgc"),
    "cppgc": ("V8_CPPGC_SOURCES", "v8_cppgc"),  # older name
    "v8_compiler": ("V8_COMPILER_SOURCES", "v8_compiler"),
    "v8_base_without_compiler": ("V8_BASE_SOURCES", "v8_base_without_compiler"),
    "v8_base": ("V8_BASE_SOURCES", "v8_base_without_compiler"),  # some versions
    "v8_initializers": ("V8_INITIALIZERS_SOURCES", "v8_initializers"),
    "v8_init": ("V8_INIT_SOURCES", "v8_init"),
    "v8_snapshot": ("V8_SNAPSHOT_SOURCES", "v8_snapshot"),
    "d8": ("V8_D8_SOURCES", "d8"),
    "torque": ("V8_TORQUE_COMPILER_SOURCES", "torque"),
    "torque-compiler": ("V8_TORQUE_COMPILER_SOURCES", "torque"),
    "mksnapshot": ("V8_MKSNAPSHOT_SOURCES", "mksnapshot"),
    "bytecode_builtins_list_generator": (
        "V8_BYTECODE_BUILTINS_LIST_GENERATOR_SOURCES",
        "bytecode_builtins_list_generator",
    ),
}


def extract_all_sources(source_dir: str, features: dict) -> dict:
    """Extract sources for all targets from BUILD.gn."""
    gn_path = os.path.join(source_dir, "BUILD.gn")
    if not os.path.exists(gn_path):
        print(f"Error: {gn_path} not found", file=sys.stderr)
        return {}

    # Set up condition based on features
    overrides = {}
    if features:
        feat = features.get("features", {})
        overrides["v8_enable_maglev"] = feat.get("maglev", False)
        overrides["v8_enable_sparkplug"] = feat.get("sparkplug", True)
        overrides["v8_enable_webassembly"] = feat.get("webassembly", True)
        overrides["v8_enable_i18n_support"] = feat.get("i18n", True)
        overrides["v8_enable_sandbox"] = feat.get("sandbox", False)

    condition = GnCondition(overrides)
    parser = GnParser(gn_path, condition)

    results = {}
    all_gn_targets = parser.get_targets()
    print(f"Found {len(all_gn_targets)} targets in BUILD.gn")

    for gn_name, (cmake_var, cmake_target) in TARGET_MAP.items():
        sources = parser.get_sources(gn_name)
        if sources:
            # Verify files exist
            verified = []
            missing = []
            for src in sources:
                full_path = os.path.join(source_dir, src)
                if os.path.exists(full_path):
                    verified.append(src)
                else:
                    missing.append(src)

            if missing:
                print(f"  {gn_name}: {len(missing)} missing files (skipped)")
                for m in missing[:5]:
                    print(f"    - {m}")
                if len(missing) > 5:
                    print(f"    ... and {len(missing) - 5} more")

            if verified:
                if cmake_var in results:
                    results[cmake_var].extend(verified)
                else:
                    results[cmake_var] = verified
                print(f"  {gn_name} -> {cmake_var}: {len(verified)} files")

    return results


def generate_sources_cmake(sources: dict, version: str) -> str:
    """Generate cmake/sources.cmake content."""
    date = datetime.now().strftime("%Y-%m-%d")
    lines = [
        f"# V8 {version} source file lists for Windows x64 MSVC",
        f"# Auto-generated by scripts/generate_sources.py on {date}",
        f"# Review and adjust as needed — the GN parser may miss edge cases.",
        "",
        '# Helper macro: prepend V8_ROOT to each path',
        "macro(v8_src VAR)",
        '  set(_files "")',
        "  foreach(_f ${ARGN})",
        '    list(APPEND _files "${V8_ROOT}/${_f}")',
        "  endforeach()",
        "  set(${VAR} ${_files})",
        "endmacro()",
        "",
    ]

    # Output each target's sources
    section_order = [
        "V8_LIBBASE_SOURCES",
        "V8_LIBPLATFORM_SOURCES",
        "V8_LIBSAMPLER_SOURCES",
        "V8_BIGINT_SOURCES",
        "V8_HEAP_BASE_SOURCES",
        "V8_CPPGC_SOURCES",
        "V8_COMPILER_SOURCES",
        "V8_BASE_SOURCES",
        "V8_INITIALIZERS_SOURCES",
        "V8_INIT_SOURCES",
        "V8_SNAPSHOT_SOURCES",
        "V8_D8_SOURCES",
        "V8_TORQUE_COMPILER_SOURCES",
        "V8_MKSNAPSHOT_SOURCES",
        "V8_BYTECODE_BUILTINS_LIST_GENERATOR_SOURCES",
    ]

    for var_name in section_order:
        if var_name not in sources:
            continue
        file_list = sorted(set(sources[var_name]))
        lines.append(f"# ---- {var_name} ({len(file_list)} files) ----")
        lines.append(f"v8_src({var_name}")
        for f in file_list:
            lines.append(f"  {f}")
        lines.append(")")
        lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate cmake/sources.cmake from V8 BUILD.gn"
    )
    parser.add_argument("--source-dir", required=True, help="Path to V8 source tree")
    parser.add_argument("--features", help="Path to version_features.json")
    parser.add_argument(
        "--output", default="cmake/sources.cmake", help="Output file path"
    )
    args = parser.parse_args()

    features = {}
    if args.features and os.path.exists(args.features):
        with open(args.features, "r") as f:
            features = json.load(f)

    version = features.get("version", "unknown")
    if version == "unknown":
        # Try reading from source
        vh = os.path.join(args.source_dir, "include", "v8-version.h")
        if os.path.exists(vh):
            import importlib.util
            spec = importlib.util.spec_from_file_location(
                "detect", os.path.join(os.path.dirname(__file__), "detect_features.py")
            )
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            v = mod.read_version(args.source_dir)
            if v:
                version = v["string"]

    print(f"Generating sources.cmake for V8 {version}")
    print(f"Source dir: {args.source_dir}")

    sources = extract_all_sources(args.source_dir, features)
    if not sources:
        print("Error: No sources extracted", file=sys.stderr)
        sys.exit(1)

    total = sum(len(v) for v in sources.values())
    print(f"\nTotal: {total} source files across {len(sources)} targets")

    content = generate_sources_cmake(sources, version)
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w") as f:
        f.write(content)
    print(f"Written to {args.output}")


if __name__ == "__main__":
    main()
