#!/usr/bin/env python3
"""Generate fetch_deps.py for a specific V8 version by parsing its DEPS file.

Fetches the DEPS file from the V8 Git repository for the given version tag
and generates a standalone fetch_deps.py that downloads V8 source and all
required third-party dependencies.
"""

import argparse
import ast
import base64
import json
import os
import re
import sys
import urllib.request


GOOGLESOURCE_BASE = "https://chromium.googlesource.com/v8/v8"


def fetch_deps_file(version: str) -> str:
    """Fetch the DEPS file content for a V8 version tag."""
    # Try tag format: X.Y.Z.W or X.Y.Z
    for tag in [version, version.rsplit(".", 1)[0]]:
        url = f"{GOOGLESOURCE_BASE}/+/refs/tags/{tag}/DEPS?format=TEXT"
        try:
            req = urllib.request.Request(url)
            with urllib.request.urlopen(req, timeout=30) as resp:
                return base64.b64decode(resp.read()).decode("utf-8")
        except Exception:
            continue

    # Try branch-heads
    major_minor = ".".join(version.split(".")[:2])
    url = f"{GOOGLESOURCE_BASE}/+/refs/branch-heads/{major_minor}/DEPS?format=TEXT"
    try:
        req = urllib.request.Request(url)
        with urllib.request.urlopen(req, timeout=30) as resp:
            return base64.b64decode(resp.read()).decode("utf-8")
    except Exception:
        pass

    return None


def parse_deps(deps_content: str) -> dict:
    """Parse the DEPS file to extract dependency URLs and revisions."""
    deps = {}

    # The DEPS file is a Python-like dict. Extract the 'deps' section.
    # We look for patterns like:
    #   'v8/third_party/foo': {
    #     'url': 'https://chromium.googlesource.com/foo.git@HASH',
    #   }
    # or simpler:
    #   'v8/third_party/foo': 'https://chromium.googlesource.com/foo.git@HASH',

    # Extract URL@hash patterns
    pattern = re.compile(
        r"'(?:v8/)?third_party/([^']+)':\s*(?:\{[^}]*'url':\s*)?'([^']+@[a-f0-9]+)'"
    )
    for m in pattern.finditer(deps_content):
        name = m.group(1).split("/")[0]  # e.g., "icu/source" -> "icu"
        url_hash = m.group(2)
        if "@" in url_hash:
            url, commit = url_hash.rsplit("@", 1)
            deps[name] = {"url": url, "commit": commit}

    # Also look for direct Var() references and simple string deps
    simple_pattern = re.compile(
        r"'(?:v8/)?third_party/([^'/]+)(?:/[^']*)?':\s*'([^']+\.git)@([a-f0-9]+)'"
    )
    for m in simple_pattern.finditer(deps_content):
        name = m.group(1)
        if name not in deps:
            deps[name] = {"url": m.group(2), "commit": m.group(3)}

    return deps


def generate_fetch_script(version: str, v8_commit: str, deps: dict) -> str:
    """Generate the fetch_deps.py script content."""
    # Map dep names to our expected directory structure
    known_deps = {
        "abseil-cpp": "abseil-cpp",
        "icu": "icu",
        "zlib": "zlib",
        "googletest": "googletest",
        "highway": "highway",
        "simdutf": "simdutf",
        "fp16": "fp16",
        "dragonbox": "dragonbox",
        "fast_float": "fast_float",
    }

    deps_entries = []
    for name, info in sorted(deps.items()):
        mapped = known_deps.get(name)
        if mapped:
            deps_entries.append(
                f'    "{mapped}": {{\n'
                f'        "url": "{info["url"]}",\n'
                f'        "commit": "{info["commit"]}",\n'
                f'        "path": "v8-src/third_party/{name}",\n'
                f"    }},"
            )

    deps_block = "\n".join(deps_entries)

    return f'''#!/usr/bin/env python3
"""Fetch V8 {version} source and third-party dependencies.

Auto-generated by scripts/generate_fetch_deps.py
"""

import os
import subprocess
import sys

V8_VERSION = "{version}"
V8_REPO = "https://chromium.googlesource.com/v8/v8.git"
V8_TAG = "{version}"

DEPS = {{
{deps_block}
}}


def run(cmd, **kwargs):
    print(f"  $ {{' '.join(cmd)}}")
    subprocess.check_call(cmd, **kwargs)


def fetch_v8():
    if os.path.isdir("v8-src"):
        print("v8-src/ already exists, checking version...")
        # Could verify version here
        return
    print(f"Cloning V8 {{V8_VERSION}}...")
    run(["git", "clone", "--depth=1", "--branch", V8_TAG, V8_REPO, "v8-src"])


def fetch_deps():
    for name, info in DEPS.items():
        path = info["path"]
        if os.path.isdir(path):
            print(f"  {{name}}: already exists at {{path}}")
            continue
        print(f"  {{name}}: cloning...")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        run(["git", "clone", info["url"], path])
        run(["git", "checkout", info["commit"]], cwd=path)


def main():
    print(f"Fetching V8 {{V8_VERSION}} and dependencies...")
    fetch_v8()
    print("\\nFetching third-party dependencies...")
    fetch_deps()
    print("\\nDone!")


if __name__ == "__main__":
    main()
'''


def main():
    parser = argparse.ArgumentParser(
        description="Generate fetch_deps.py for a V8 version"
    )
    parser.add_argument("--version", required=True, help="V8 version (e.g., 13.6.233.17)")
    parser.add_argument("--output", default="fetch_deps.py", help="Output file path")
    parser.add_argument("--deps-file", help="Use local DEPS file instead of fetching")
    args = parser.parse_args()

    if args.deps_file:
        with open(args.deps_file, "r") as f:
            deps_content = f.read()
    else:
        print(f"Fetching DEPS for V8 {args.version}...")
        deps_content = fetch_deps_file(args.version)
        if deps_content is None:
            print(f"Error: Could not fetch DEPS for V8 {args.version}", file=sys.stderr)
            sys.exit(1)

    deps = parse_deps(deps_content)
    print(f"Found {len(deps)} third-party dependencies")
    for name in sorted(deps.keys()):
        print(f"  - {name}: {deps[name]['commit'][:12]}")

    script = generate_fetch_script(args.version, "", deps)
    with open(args.output, "w") as f:
        f.write(script)
    print(f"\nGenerated {args.output}")


if __name__ == "__main__":
    main()
