# =============================================================================
# Snapshot generation
# =============================================================================
# V8 uses "snapshots" to speed up startup. The snapshot contains a serialized
# heap with pre-compiled builtins. The flow is:
#
#   1. Build mksnapshot executable (links against full V8)
#   2. Run mksnapshot to produce snapshot.cc and embedded.S
#   3. Assemble embedded.S with MASM (ml64 on Windows x64)
#   4. Compile snapshot.cc
#   5. Link into final v8 library
# =============================================================================

if(NOT V8_ENABLE_SNAPSHOT)
  # No-snapshot build: use empty snapshot
  v8_src(_snapshot_nosnapshot_sources
    src/snapshot/snapshot-empty.cc
    src/snapshot/embedded/embedded-empty.cc
  )
  add_library(v8_snapshot STATIC
    ${V8_SNAPSHOT_SOURCES}
    ${_snapshot_nosnapshot_sources}
  )
  target_link_libraries(v8_snapshot PUBLIC v8_base v8_init)
  add_dependencies(v8_snapshot run_torque)
else()
  # ==========================================================================
  # Build mksnapshot executable
  # ==========================================================================
  add_executable(mksnapshot ${V8_MKSNAPSHOT_SOURCES})
  if(WIN32)
    target_link_libraries(mksnapshot PRIVATE
      v8_base_without_compiler
      v8_compiler
      v8_init
      v8_initializers
      v8_libbase
      v8_libplatform
      v8_libsampler
      v8_zlib_google
    )
    if(V8_ENABLE_I18N)
      target_link_libraries(mksnapshot PRIVATE icu_interface)
    endif()
  else()
    set(_mksnapshot_libs
      v8_base_without_compiler v8_compiler v8_init v8_initializers
      v8_libbase v8_libplatform v8_libsampler v8_bigint v8_cppgc
      v8_heap_base v8_zlib v8_zlib_google
    )
    if(V8_ENABLE_I18N)
      list(APPEND _mksnapshot_libs icu_interface)
    endif()
    if(TARGET v8_simdutf)
      list(APPEND _mksnapshot_libs v8_simdutf)
    endif()
    if(TARGET v8_highway)
      list(APPEND _mksnapshot_libs v8_highway)
    endif()
    target_link_libraries(mksnapshot PRIVATE -Wl,--start-group ${_mksnapshot_libs} -Wl,--end-group)
    target_link_libraries(mksnapshot PRIVATE pthread dl)
  endif()
  # MSVC: mksnapshot sources share some torque-generated constants with v8_base
  if(MSVC)
    target_link_options(mksnapshot PRIVATE /FORCE:MULTIPLE)
  endif()
  add_dependencies(mksnapshot run_torque generate_bytecodes_builtins_list generate_regexp_special_case)

  # ==========================================================================
  # Run mksnapshot to generate snapshot.cc and embedded.S
  # ==========================================================================
  set(SNAPSHOT_CC "${V8_GENERATED_DIR}/snapshot.cc")
  set(EMBEDDED_S "${V8_GENERATED_DIR}/embedded.S")

  if(WIN32)
    set(V8_TARGET_OS_FLAG "win")
  else()
    set(V8_TARGET_OS_FLAG "linux")
  endif()

  add_custom_command(
    OUTPUT "${SNAPSHOT_CC}" "${EMBEDDED_S}"
    COMMAND $<TARGET_FILE:mksnapshot>
      --startup_src "${SNAPSHOT_CC}"
      --embedded_src "${EMBEDDED_S}"
      --embedded_variant Default
      --target_arch x64
      --target_os ${V8_TARGET_OS_FLAG}
    DEPENDS mksnapshot
    WORKING_DIRECTORY "${V8_ROOT}"
    COMMENT "Generating V8 snapshot"
  )

  add_custom_target(generate_snapshot DEPENDS "${SNAPSHOT_CC}" "${EMBEDDED_S}")

  # ==========================================================================
  # Assemble embedded.S
  # On Windows with MSVC, we need to preprocess/assemble the .S file.
  # embedded.S generated by mksnapshot on Windows uses MASM-compatible syntax.
  # ==========================================================================

  # Build embedded.S as a separate object to avoid CXX flag leakage
  add_library(v8_embedded_asm OBJECT "${EMBEDDED_S}")
  set_target_properties(v8_embedded_asm PROPERTIES
    LINKER_LANGUAGE CXX
    COMPILE_OPTIONS ""
    COMPILE_DEFINITIONS ""
  )
  if(WIN32)
    set_source_files_properties("${EMBEDDED_S}" PROPERTIES
      LANGUAGE ASM_MASM
      GENERATED TRUE
      COMPILE_FLAGS ""
    )
  else()
    set_source_files_properties("${EMBEDDED_S}" PROPERTIES
      LANGUAGE ASM
      GENERATED TRUE
      COMPILE_FLAGS ""
    )
  endif()
  add_dependencies(v8_embedded_asm generate_snapshot)

  # ==========================================================================
  # v8_snapshot library
  # ==========================================================================
  add_library(v8_snapshot STATIC
    ${V8_SNAPSHOT_SOURCES}
    "${SNAPSHOT_CC}"
    $<TARGET_OBJECTS:v8_embedded_asm>
  )
  target_link_libraries(v8_snapshot PUBLIC v8_base)
  add_dependencies(v8_snapshot generate_snapshot run_torque)

  set_source_files_properties("${SNAPSHOT_CC}" PROPERTIES GENERATED TRUE)
endif()

# =============================================================================
# Final V8 combined library
# =============================================================================
# This is the main target that consumers should link against.
# It bundles everything needed for a complete V8 build.
# =============================================================================
add_library(v8 INTERFACE)
if(WIN32)
  target_link_libraries(v8 INTERFACE
    v8_base
    v8_snapshot
    v8_initializers
    v8_libplatform
    v8_libsampler
    v8_libbase
    v8_zlib_google
  )
else()
  target_link_libraries(v8 INTERFACE
    -Wl,--start-group
    v8_base_without_compiler
    v8_compiler
    v8_snapshot
    v8_initializers
    v8_libplatform
    v8_libsampler
    v8_libbase
    v8_zlib_google
    -Wl,--end-group
    pthread dl
  )
endif()

# ---------------------------------------------------------------------------
# Public interface for consumers (add_subdirectory / find_package)
# ---------------------------------------------------------------------------
# Include path: only the public API headers
target_include_directories(v8 INTERFACE
  "$<BUILD_INTERFACE:${V8_ROOT}/include>"
)

# Embedder-visible compile definitions that must match the V8 build.
# V8 checks these at Isolate creation and will abort on mismatch.
set(_v8_public_defs
  V8_COMPRESS_POINTERS
  V8_COMPRESS_POINTERS_IN_SHARED_CAGE
  V8_31BIT_SMIS_ON_64BIT_ARCH
)
if(V8_ENABLE_SANDBOX)
  list(APPEND _v8_public_defs V8_ENABLE_SANDBOX)
endif()
target_compile_definitions(v8 INTERFACE ${_v8_public_defs})

# MSVC: consumers need /Zc:__cplusplus so V8 headers pass __cplusplus check
if(MSVC)
  target_compile_options(v8 INTERFACE /Zc:__cplusplus)
endif()

# =============================================================================
# Smoke test: hello_v8
# =============================================================================
if(EXISTS "${CMAKE_SOURCE_DIR}/test/hello_v8.cc")
  add_executable(hello_v8 "${CMAKE_SOURCE_DIR}/test/hello_v8.cc")
  target_link_libraries(hello_v8 PRIVATE v8)
  if(MSVC)
    target_link_options(hello_v8 PRIVATE /FORCE:MULTIPLE)
  endif()
endif()

# Install rules are in cmake/install.cmake
