# =============================================================================
# Snapshot generation
# =============================================================================
# V8 uses "snapshots" to speed up startup. The snapshot contains a serialized
# heap with pre-compiled builtins. The flow is:
#
#   1. Build mksnapshot executable (links against full V8)
#   2. Run mksnapshot to produce snapshot.cc and embedded.S
#   3. Assemble embedded.S with MASM (ml64 on Windows x64)
#   4. Compile snapshot.cc
#   5. Link into final v8 library
# =============================================================================

if(NOT V8_ENABLE_SNAPSHOT)
  # No-snapshot build: use empty snapshot
  v8_src(_snapshot_nosnapshot_sources
    src/snapshot/snapshot-empty.cc
    src/snapshot/embedded/embedded-empty.cc
  )
  add_library(v8_snapshot STATIC
    ${V8_SNAPSHOT_SOURCES}
    ${_snapshot_nosnapshot_sources}
  )
  target_link_libraries(v8_snapshot PUBLIC v8_base v8_init)
  add_dependencies(v8_snapshot run_torque)
else()
  # ==========================================================================
  # Build mksnapshot executable
  # ==========================================================================
  add_executable(mksnapshot ${V8_MKSNAPSHOT_SOURCES})
  target_link_libraries(mksnapshot PRIVATE
    v8_base_without_compiler
    v8_compiler
    v8_init
    v8_initializers
    v8_libbase
    v8_libplatform
    v8_libsampler
    v8_abseil
    v8_zlib_google
  )
  if(V8_ENABLE_I18N)
    target_link_libraries(mksnapshot PRIVATE icu_interface)
  endif()
  # MSVC: mksnapshot sources share some torque-generated constants with v8_base
  if(MSVC)
    target_link_options(mksnapshot PRIVATE /FORCE:MULTIPLE)
  endif()
  add_dependencies(mksnapshot run_torque generate_bytecodes_builtins_list generate_regexp_special_case)

  # ==========================================================================
  # Run mksnapshot to generate snapshot.cc and embedded.S
  # ==========================================================================
  set(SNAPSHOT_CC "${V8_GENERATED_DIR}/snapshot.cc")
  set(EMBEDDED_S "${V8_GENERATED_DIR}/embedded.S")

  add_custom_command(
    OUTPUT "${SNAPSHOT_CC}" "${EMBEDDED_S}"
    COMMAND $<TARGET_FILE:mksnapshot>
      --startup_src "${SNAPSHOT_CC}"
      --embedded_src "${EMBEDDED_S}"
      --embedded_variant Default
      --target_arch x64
      --target_os win
    DEPENDS mksnapshot
    WORKING_DIRECTORY "${V8_ROOT}"
    COMMENT "Generating V8 snapshot"
  )

  add_custom_target(generate_snapshot DEPENDS "${SNAPSHOT_CC}" "${EMBEDDED_S}")

  # ==========================================================================
  # Assemble embedded.S
  # On Windows with MSVC, we need to preprocess/assemble the .S file.
  # embedded.S generated by mksnapshot on Windows uses MASM-compatible syntax.
  # ==========================================================================

  # Build embedded.S as a separate MASM object to avoid CXX flag leakage
  add_library(v8_embedded_asm OBJECT "${EMBEDDED_S}")
  set_target_properties(v8_embedded_asm PROPERTIES
    LINKER_LANGUAGE CXX
    COMPILE_OPTIONS ""
    COMPILE_DEFINITIONS ""
  )
  set_source_files_properties("${EMBEDDED_S}" PROPERTIES
    LANGUAGE ASM_MASM
    GENERATED TRUE
    COMPILE_FLAGS ""
  )
  add_dependencies(v8_embedded_asm generate_snapshot)

  # ==========================================================================
  # v8_snapshot library
  # ==========================================================================
  add_library(v8_snapshot STATIC
    ${V8_SNAPSHOT_SOURCES}
    "${SNAPSHOT_CC}"
    $<TARGET_OBJECTS:v8_embedded_asm>
  )
  target_link_libraries(v8_snapshot PUBLIC v8_base)
  add_dependencies(v8_snapshot generate_snapshot run_torque)

  set_source_files_properties("${SNAPSHOT_CC}" PROPERTIES GENERATED TRUE)
endif()

# =============================================================================
# Final V8 combined library
# =============================================================================
# This is the main target that consumers should link against.
# It bundles everything needed for a complete V8 build.
# =============================================================================
add_library(v8 INTERFACE)
target_link_libraries(v8 INTERFACE
  v8_base
  v8_snapshot
  v8_initializers
  v8_libplatform
  v8_libbase
)

# =============================================================================
# Install rules
# =============================================================================
install(DIRECTORY "${V8_ROOT}/include/"
  DESTINATION include/v8
  FILES_MATCHING PATTERN "*.h"
)
